services:

  frontend:
    build:
      context: frontend/
    # image: true-home-frontend:1.2.7
    environment:
      TZ: Asia/Shanghai
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '9527:80'
    networks:
      - true-home

  backend:
    build:
      context: backend/
    # image: true-home-backend:0.0.1
    environment:
      TZ: Asia/Shanghai
      CASBIN_MODEL: 'model.conf'
      NODE_ENV: production
      APP_PORT: 9528
      DOC_SWAGGER_ENABLE: 'true'
      DOC_SWAGGER_PATH: 'api-docs'
      DATABASE_URL: 'postgresql://truehome:truehome@123.@postgres:5432/true-home-nest-backend?schema=public'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      REDIS_PASSWORD: '123456'
      REDIS_DB: 1
      JWT_SECRET: 'JWT_SECRET-true-home@123456!@#.'
      JWT_EXPIRE_IN: 3600
      REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET-true-home@123456!@#.'
      REFRESH_TOKEN_EXPIRE_IN: 7200
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '9528:9528'
    networks:
      - true-home
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:9528/v1/route/getConstantRoutes"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    cpus: 2

  postgres:
    image: postgres:16.3
    environment:
      TZ: Asia/Shanghai
      POSTGRES_PASSWORD: truehome@123.
      POSTGRES_USER: truehome
      POSTGRES_DB: true-home-nest-backend
    ports:
      - '25432:5432'
    volumes:
      - true-home-postgres_data:/usr/share/docker/postgresql
      - ./deploy/postgres:/docker-entrypoint-initdb.d
    networks:
      - true-home
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U truehome -d true-home-nest-backend"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: bitnami/pgbouncer:1.23.1
    container_name: pgbouncer
    hostname: pgbouncer
    restart: always
    environment:
      - PGBOUNCER_DATABASE=*
      - POSTGRESQL_USERNAME=truehome
      - POSTGRESQL_PASSWORD=truehome@123.
      - POSTGRESQL_DATABASE=true-home-nest-backend
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
    ports:
      - 6432:6432
    networks:
      - true-home

  redis:
    image: redis/redis-stack:7.2.0-v11
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass 123456
    ports:
      - '26379:6379'
    volumes:
      - true-home-redis_data:/data
    networks:
      - true-home
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  true-home-postgres_data:
  true-home-redis_data:

networks:
  true-home:
