import { Prisma } from '@prisma/client';

import { prisma } from '../helper';

export const initMyHomeContactInfo = async () => {
  const data: Prisma.MyHomeContactInfoCreateInput[] = [
    {
      id: '1',
      userId: '1',
      icon: 'mdi:phone',
      contactName: '手机',
      contact: '138 1234 5678',
      showContactName: false,
      link: 'tel:13812345678',
      linkType: 'url',
      status: 'DISABLED',
      createdAt: new Date('2000-01-01T00:00:00.000Z'),
      createdBy: '-1',
    },
    {
      id: '2',
      userId: '1',
      icon: 'mdi:email',
      contactName: '邮箱',
      contact: 'user@example.com',
      showContactName: false,
      link: 'mailto:user@example.com',
      linkType: 'url',
      status: 'DISABLED',
      createdAt: new Date('2000-01-01T00:00:00.000Z'),
      createdBy: '-1',
    },
    {
      id: '3',
      userId: '1',
      icon: 'mdi:github',
      contactName: 'GitHub',
      contact: 'FeeGeek',
      showContactName: false,
      link: 'https://github.com/FeeGeek',
      linkType: 'url',
      status: 'ENABLED',
      createdAt: new Date('2000-01-01T00:00:00.000Z'),
      createdBy: '-1',
    },
    {
      id: '4',
      userId: '1',
      icon: 'mdi:map-marker',
      contactName: '地址',
      contact: '上海市浦东新区',
      showContactName: false,
      link: 'https://maps.google.com/',
      linkType: 'copy',
      status: 'DISABLED',
      createdAt: new Date('2000-01-01T00:00:00.000Z'),
      createdBy: '-1',
    },
    {
      id: '5',
      userId: '1',
      icon: 'mdi:qqchat',
      contactName: 'QQ',
      contact: '9329009',
      showContactName: false,
      link: '9329009',
      linkType: 'copy',
      status: 'ENABLED',
      createdAt: new Date('2000-01-01T00:00:00.000Z'),
      createdBy: '-1',
    },
    {
      id: '6',
      userId: '1',
      icon: 'mdi:wechat',
      contactName: '微信',
      contact: 'FeeGeek',
      showContactName: false,
      link: 'FeeGeek',
      linkType: 'copy',
      status: 'DISABLED',
      createdAt: new Date('2000-01-01T00:00:00.000Z'),
      createdBy: '-1',
    },
    {
      id: '7',
      userId: '1',
      icon: 'mdi:wechat',
      contactName: '微信群',
      contact: 'FeeGeek',
      showContactName: true,
      link: 'http://iph.href.lu/300x300',
      linkType: 'img',
      status: 'ENABLED',
      createdAt: new Date('2000-01-01T00:00:00.000Z'),
      createdBy: '-1',
    },
    {
      id: '8',
      userId: '1',
      icon: 'mdi:fire-circle',
      contactName: '火花',
      contact: 'FeeGeek',
      showContactName: true,
      link: 'http://iph.href.lu/400x900',
      linkType: 'img',
      status: 'DISABLED',
      createdAt: new Date('2000-01-01T00:00:00.000Z'),
      createdBy: '-1',
    },
  ];

  return prisma.myHomeContactInfo.createMany({ data });
};
